In [2]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [5]:
import numpy
n=numpy.arange(27)

In [12]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
m=numpy.asarray([[123,12,123,12,33],[],[]])

In [15]:
type(m)

numpy.ndarray

In [22]:
import cv2

In [46]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [35]:
cv2.imwrite("newsmallgray.png",im_g)

True

In [48]:
im_g[2,4]

182

In [57]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [59]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [61]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [64]:
ims=numpy.hstack((im_g,im_g))
print(ims)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [66]:
lst=numpy.vsplit(ims,3)
lst[0]

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8)